name: ally
description: A new Flutter project for women's safety.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15
  geolocator: ^9.0.1
  permission_handler: ^12.0.0+1
  url_launcher: ^6.2.5
  flutter_contacts: ^1.1.7
  cupertino_icons: ^1.0.2
  audioplayers: ^5.2.1
  vibration: ^3.1.3
  flutter_local_notifications: ^17.1.2
  sqflite: ^2.3.0
  path: any
  cloud_firestore: ^5.6.7
  firebase_core: ^3.13.0
  firebase_auth: 5.5.3
  location: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/siren.mp3

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo.png
